# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d231eeee1158f2e064b3d00ac93f4d4c2980226ca9e16c769ae856192c07ff68e223ed176a84cc52f5eba003541baa1a29c3cddb12b93c6a7ba6f1face1e0716

test:
  secret_key_base: cd633979a3e343db88f3bbc7f802002c5569b947482f1985de5ab4924ad4ba73407dda8542872c0d9dc47ede277b8ce4db3e502aca38c803ee7aeaaf33dd6565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
